displayName=Bankstanding
author=mhollink
description=Gain (fake) experience with doing absolutely nothing
tags=bankstanding, xp, experience, nothing, afk
plugins=dev.hollink.bankstanding.BankstandingPlugin